### ISSUE TITLE
How to do a page break ??

### ISSUE THREAD

**Issue by sinjuangajan** [cognitom/paper-css#1]
I want page break for after each content for pages. How to implement it.

**Comment by koki-h** [comment]
Hello.
It will insert a page break after a element of .sheet class. 

Here is sample.

```
<section class="sheet">
  <!-- first page -->
</section>
<section class="sheet">
  <!-- second page -->
</section>
      :
      :
```

**Comment by cognitom** [comment]
@koki-h thanks for explaining it :smile: 
@sinju have a look at this line:
https://github.com/cognitom/paper-css/blob/master/paper.css#L9

**Comment by salim-dev** [comment]
Hello 
is what you can add in class sheet :
            break-after: page;
              /* for Firefox : */
            page-break-after: always;
           /* for WebKit : */
            -webkit-break-after: page;
thank
