### ISSUE TITLE
div support

### ISSUE THREAD

**Issue by nueko** [cognitom/paper-css#17]
Hi, greate if we support div element print, not only body.

**Comment by cognitom** [comment]
I'm not sure...
If you think about printing a part of entire document, it may needs some JavaScript hack.

**Note**: And also I got to mention about the brower limitation: we can't set multiple page size in one document. 

I'll close this issue, but feel free to reopen. Thanks.

**Comment by Simon-Tang** [comment]
For what it's worth, only CSS is needed to only print some elements, using `@media print`. (Although you'd still use JS to specify specific pages).

MDN reference: https://developer.mozilla.org/en-US/docs/Web/CSS/@media
