### ISSUE TITLE
Wrong number of pages created

### ISSUE THREAD

**Issue by focussing** [cognitom/paper-css#18]
Hello!

Thank you for this great css!

I have the following issue; when I create 2 A4 sheets, the print preview (option-P) on Mac shows 3 pages, nr 1 and nr 3 are correct, page nr 2 is an empty sheet.

I set the padding to 25 mm which is way larger than the real margins of my printer.

**Comment by cognitom** [comment]
Sorrry for late reply. It looks that it depends on the content.
`paper-css` defines just the size of the paper. If the content of a *sheet* is bigger than the hight of the paper specified, your browser break its page automatically.
