### ISSUE TITLE
How about centering the sheet in the center of the screen?

### ISSUE THREAD

**Issue by arivera12** [cognitom/paper-css#20]
I think for visual purpose for the clients/users centering the sheet is great for them. So I added this small line of css for centering the sheets without affecting the print result.
```
.sheet {
     margin: 0 auto;
}
```
I have used this small brilliant perfect fit css lib combined with normalize.css for all my docs and they just render perfectly on every browser! Thanks in advance!

**Comment by cognitom** [comment]
Thanks @arivera12.
#21 includes this change.
