### ISSUE TITLE
Using Paper-CSS With BootStrap 3

### ISSUE THREAD

**Issue by marcoczen** [cognitom/paper-css#22]
Hi, Do you have an example , showing paper.css in a bootstrap 3 environment ?
How do we use paper.css in a grid ( table-less layout ) ?

**Comment by cognitom** [comment]
Hi @marcoczen, I recommend you to make your printing css independent from `Bootstrap`, which is not designed for printing. Even if you don't use `<table>`, feel free to style your *grid*, I think. But, how to decorate them is not the focus of this repo. I'll close this issue. Thanks.

**Comment by aynomjb** [comment]
> Hi, Do you have an example , showing paper.css in a bootstrap 3 environment ?
> How do we use paper.css in a grid ( table-less layout ) ?

remove the @media print{....} from bootstrap.css
