### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by EugeneDae** [cognitom/paper-css#24]
Just wanted to say thanks for the stylesheet 👏  I've been a web-developer for more than a half of my life and I had no idea printing from a browser could be implemented so neatly. Thanks! 👍

**Comment by gborgonovo** [comment]
Me too! I want to say thank you for this great piece of code. I use it to do photobooks like a charme!

**Comment by cognitom** [comment]
@EugeneDae @gborgonovo I'm so happy to hear you! Thank you for sharing your "thanks" 😄 
Photobooks sounds a nice application!

**Comment by gborgonovo** [comment]
Hi Tsutomu,
I have published the code of the photobook application, if you are
interested you can find it here: https://github.com/gborgonovo/photobook
It is a work in progress...
Ciao
Giorgio
