### ISSUE TITLE
When printing. It always adds an extra page.

### ISSUE THREAD

**Issue by AninaLipocheck** [cognitom/paper-css#51]
Hi,
i created a document that has 7 pages. When ever i want to print it, it adds after each page a blank page. The Preview and code looks good. I can also say, that there is no extra overlapping data.
Does anyone of you had the same problem?

Browser: Chrome

**Comment by chawilai** [comment]
got same problem can anyone know how to fix it

**Comment by AninaLipocheck** [comment]
i found the problem on my side. i have on each page 3 sections (header, footer and a main part). I had to specify the height of each seaction. percentage values worked perfectly.

**Comment by warmwhisky** [comment]
Try putting `style="contain: size;"` or `style="contain: strict;"` around the parent element

**Comment by chawilai** [comment]
> got same problem can anyone know how to fix it

Actually, I finally found the solution just put this style on the page, the point is we have to make sure there is no margin and padding.

  @media print {
    html,
    body {
      height: 100vh;
      margin: 0 !important;
      padding: 0 !important;
      overflow: hidden;
    }
  }
